# Generated by Django 2.2.7 on 2019-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
